### PR TITLE
Remove demo patches along with dependencies

### PR DESCRIPTION
**Pull request by lindboe**
## Please verify the following:

- [x] `yarn test` **jest** tests pass with new tests, if relevant
- [x] `yarn lint` **eslint** checks pass with new code, if relevant
- [x] `yarn format:check` **prettier** checks pass with new code, if relevant
- [x] `README.md` (or relevant documentation) has been updated with your changes

## Describe your PR

While testing fixes to component testing config, I found that a project generated with `ignite-cli@latest` and `--removeDemo` would have an error when installing a new dependency, because there was a patch for `react-native-drawer-layout`, which had been removed from the project:

```
patch-package 8.0.0
Applying patches...
Error: Patch file found for package react-native-drawer-layout which is not present at node_modules/react-native-drawer-layout
---
```

So now, in addition to removing demo-only dependencies, we'll remove any matching patch files from the project.

### CODE REVIEW

**Review by fpena — APPROVED** [review]
Looks good! 🚀

**Review by frankcalise — APPROVED** [review]
Sweet, thanks for this! Good thinking!

**Comment by mazenchami** [comment]
did we test this when it comes to RTL? i'm not sure if its the same one, but Leon had put in a patch for `react-native-drawer-layout` to fix an issue (see #2696)

**Comment by frankcalise** [comment]
The patch file is only removed when the demo boilerplate is removed (the drawer will not be present, nor the dependency)

**Comment by jorgtz** [comment]
I have an issue when I try to install a new library or reinstall dependencies after fresh creation of the project:
image
However, It passes the tests:

**Pull request merged**
