### PR TITLE
Add a demo list screen to boilerplate

### PR DESCRIPTION
**Pull request by kateinkim**
## Please verify the following:

- [x] `yarn ci:test` **jest** tests pass with new tests, if relevant
- [x] `README.md` has been updated with your changes, if relevant

## Describe your PR

Per https://github.com/infinitered/ignite/issues/1605 adds a demo list screen that fetches data from a public API. Not sure if this is the right place to put it per that discussion but I'm happy to move it wherever it should be.

Simulator Screen Shot - iPhone 11 - 2021-02-15 at 21 00 42

### CODE REVIEW

**Comment by vantuan88291** [comment]
I don't think this demo is useful. You should fetch api and use model to store data from api. This is **mobx-state-tree**

**Comment by chrispecoraro** [comment]
@kateinkim, yes, I agree with @vantuan88291. This demo is great and is badly needed, but what I'm interested in learning is how to use the MST with the API and then how to pass the data in the MST between screens using navigation, so actually, there should be two screens involved. I wish I could help, but I'm still learning.

**Comment by vantuan88291** [comment]
> @kateinkim, yes, I agree with @vantuan88291. This demo is great and is badly needed, but what I'm interested in learning is how to use the MST with the API and then how to pass the data in the MST between screens using navigation, so actually, there should be two screens involved. I wish I could help, but I'm still learning.

i have some repo on my git using mobx state tree, you can refer it

**Comment by kateinkim** [comment]
@chrispecoraro @vantuan88291 I hear you. I'm still learning myself. I was trying to balance between adding the example and cutting down on the need to delete across multiple files per the original issue discussion. I can definitely see how it would be more useful to include MST integration. Maybe @jamonholmgren and/or @bryanstearns can chime in with some guidance?

**Comment by syahnur197** [comment]
@chrispecoraro @kateinkim I've added an example on how to use the demo app with MST and API Sauce as recommended by the boilerplate itself. From what I understand, you can just import the `CharacterStore` into anywhere in your screens and component, you would have access to the characters in the store

**Comment by kateinkim** [comment]
@syahnur197 Thanks for the MST help. 😄 I made some additional updates at @jamonholmgren's suggestion.

**Review by jamonholmgren — APPROVED** [review]
This looks really clean. Nice job @kateinkim !

**Review by leonskim — APPROVED** [review]
Nicely done! This is a neat example that would really help who just stepped in RN, Ignite and MST. Thanks for your contributions! 🥇

**Pull request merged**
