### PR TITLE
Remove ava global dependencies

### PR DESCRIPTION
**Pull request by guidiego**
## Please verify the following:
- [ x ] Everything works on iOS/Android
- [ x ] `ignite-base` **ava** tests pass
- [ x ] `fireDrill.sh` passed

## Describe your PR
I have some problems with globals during the installation of the project, so I decided to remove globals dependencies from `package.json`, I start for `ava` but let me know if has something more that I can change :)

### CODE REVIEW

**Comment by guidiego** [comment]
I was looking alternatives for `xdg-open`, something that I can install by npm :) I found that [opn-bg](https://www.npmjs.com/package/opn-bg). If you guys have some other ideias will be nice listen that :)

**Comment by skellock** [comment]
Thanks for the `PR`.  `nyc` would also qualify for this treatment too.  Also, I'm onboard for `open-bg`.  Good find.

**Comment by guidiego** [comment]
@skellock Yeah! I think the same, after do the onboarding give me a feed back :D

**Comment by skellock** [comment]
So, hey, i tested this out.

Turns out I'm not sure any of this is needed.

These deps should be sourced from `node_modules/.bin`.   Both `nyc` and `ava` are devDeps.

I tested by `npm -g rm ava` and nyc.   

Are you running `npm` version 2 by any chance?

**Comment by guidiego** [comment]
@skellock Yeah! I saw that in this moment, when I clone into my mac and run NYC/AVA without global installation. My fault, I use `c9.io` to write in open source projects, sometimes I forgot that instances old versions of node/npm. This will be only necessary if someone wants run the project with lowest node versions.

I think that we can only consider saw `xdg-open` :)

**Comment by GantMan** [comment]
gonna close this one, in favor of whatever comes next.

**Pull request closed without merging**
