### PR TITLE
Remove deep nesting from generators

### PR DESCRIPTION
**Pull request by robinheinze**
## Please verify the following:

- [x] `yarn ci:test` **jest** tests pass with new tests, if relevant
- [x] `README.md` has been updated with your changes, if relevant

## Describe your PR

By default, we are moving away from deeply nested structure, so this moves generated components, models, and screens out of their individual named folders and into the relevant root folder instead. 

If the user prefers it the old way, the templates can be updated using front-matter and the destinationDir property:
```
destinationDir: app/models/<%= props.kebabCaseName %>/<%= props.kebabCaseName %>\"
```

## Visuals

Screen Shot 2022-09-01 at 11 16 53 AM

### CODE REVIEW

**Comment by kateinkim** [comment]
LGTM 👍🏼

**Review by kateinkim — APPROVED** [review]

**Comment by cdanwards** [comment]
In the new file structure, the files are capitalized but the generators are creating them with lower-case naming: `Pizza` vs `pizza`. Are we wanting the generators to match the provided nomenclature?

**Comment by robinheinze** [comment]
@cdanwards that's a great point. I think we should match the new pattern. I'll update this PR to do that as well.

**Comment by robinheinze** [comment]
Actually, I think I will do that in a separate PR since it's a fairly substantial change and I don't want to hold this part up in case i don't finish before EOD.

**Pull request merged**
