### PR TITLE
fix(boilerplate): bump patch-package version

### PR DESCRIPTION
**Pull request by keponk**
## Please verify the following:

- [x] `yarn test` **jest** tests pass with new tests, if relevant
- [x] `yarn lint` **eslint** checks pass with new code, if relevant
- [x] `yarn format:check` **prettier** checks pass with new code, if relevant
- [x] `README.md` (or relevant documentation) has been updated with your changes

## Describe your PR
As per #2712 , patch-package is a bit too old. I also noticed it was fixed to the specific version. I don't see a big reason for this as it is not the type of project that would break api in minor version updates so I've let it be updateable.

### CODE REVIEW

**Review by fpena — APPROVED** [review]
Looks good to me!

**Comment by lindboe** [comment]
@frankcalise any objections to merging this?

**Review by frankcalise — APPROVED** [review]

**Comment by frankcalise** [comment]
> @frankcalise any objections to merging this?

Nope, getting some deps upgraded would be good.

**Pull request merged**
