### PR TITLE
Feat: Expo 47 and react-native 0.70.5

### PR DESCRIPTION
**Pull request by frankcalise**
## Please verify the following:

- [x] `yarn test` **jest** tests pass with new tests, if relevant
- [x] `README.md` has been updated with your changes, if relevant

## Describe your PR
- Upgrades to Expo 47.0.12
- Upgrades to react-native 0.70.5 (via this [upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.69.0&to=0.70.5)

Scenarios Tested
- [x] Expo iOS
- [x] Expo Android
- [x] vanilla iOS
- [x] vanilla Android

### CODE REVIEW

**Comment by frankcalise** [comment]
One thing I've noticed so far in the demo screens, from the Components Showroom after you drag the drawer open and closed, it looks like the dim overlay (from having the drawer open) sets in after a few seconds and the list view with the components becomes harder to read.

Simulator Screen Recording - iPhone 13 - 2022-10-31 at 15 55 03

**Comment by frankcalise** [comment]
> One thing I've noticed so far in the demo screens, from the Components Showroom after you drag the drawer open and closed, it looks like the dim overlay (from having the drawer open) sets in after a few seconds and the list view with the components becomes harder to read.
> 
> Simulator Screen Recording - iPhone 13 - 2022-10-31 at 15 55 03 [ Simulator Screen Recording - iPhone 13 - 2022-10-31 at 15 55 03 ](https://user-images.githubusercontent.com/374022/199098623-4b122bf2-e1bb-4ea5-8a40-0f785ecd8d21.gif) [ ](https://user-images.githubusercontent.com/374022/199098623-4b122bf2-e1bb-4ea5-8a40-0f785ecd8d21.gif)

Was able to fix this via the `overlayColor` prop

**Comment by foratbahrani** [comment]
why isn't this merged yet?

**Review by robinheinze — APPROVED** [review]
Nice work! I checked it out and generated a few projects. Everything seems to be working great!

**Pull request merged**
