### PR TITLE
Add custom nav bar example

### PR DESCRIPTION
**Pull request by ryanlntn**
## Please verify the following:
- [ ] Everything works on iOS/Android
- [x] `ignite-base` **ava** tests pass
- [x] `fireDrill.sh` passed

## Describe your PR
Addresses #275

### CODE REVIEW

**Comment by GantMan** [comment]
## _EEEEEEEEK!_
image

albeit satisfying the requirement... kinda, umm, wat?

I now take the design crown from @justinhuskey and put it on your head ryan :)

@fvonhoven - Can we get that cool search/nav? in this PR?  
Or maybe Ryan, can we have one where the title is swapped out for an image?

**Comment by fvonhoven** [comment]
@GantMan 
alt tab

**Comment by ryanlntn** [comment]
@GantMan Better for now? 
image

I agree that search would be stellar on this screen.

**Comment by GantMan** [comment]
@fvonhoven - just do the searchbar in a separate PR
get out
😁

@ryanlntn - it needs a back button, or you're stuck there forever, right?
Also, might want to put a comment on why this one screen is different.  Maybe in NavigationRoutes.

**Comment by fvonhoven** [comment]
@Gantman I'll put the back button. Just merge this and I'll go from there

**Pull request merged**
