### PR TITLE
using `baseUrl` to avoid `../../../`

### LINKED ISSUE #1770: Use baseUrl in tsconfig for absolute paths
We should discuss/consider using `baseUrl` in our tsconfig so we can change imports like this:

```tsx
import { Thing } from "../../components/thing"
```

to this

```tsx
import { Thing } from "components/thing"
```

Docs: https://www.typescriptlang.org/tsconfig#baseUrl

### PR DESCRIPTION
**Pull request by flexbox**
## Please verify the following:

- [x] `yarn ci:test` **jest** tests pass with new tests, if relevant
- [x] `README.md` has been updated with your changes, if relevant

## Describe your PR

It the first attempt to closes #1770 

I installed the tooling with https://github.com/infinitered/ignite/pull/1886/commits/2da5b74a07812c1e941cd4a4384110a676d39102

@majidln
Before migrating the entire `/boilerplate` folder I need some inputs if you think it's in a good direction
https://github.com/infinitered/ignite/pull/1886/commits/d4f364bee4eab2a90d1c11335160cf610c25972d

Let me know in the comments 😉 

---

Nex Step:

- [ ] Fix model errors to avoid

```
 FAIL  app/models/character-store/character-store.test.ts
  ● Test suite failed to run

    [mobx-state-tree] expected mobx-state-tree type as argument 1, got undefined instead

       7 | // prettier-ignore
       8 | export const RootStoreModel = types.model("RootStore").props({
    >  9 |   characterStore: types.optional(CharacterStoreModel, {} as any),
         |                         ^
```

### CODE REVIEW

**Comment by jamonholmgren** [comment]
@flexbox On-stream I trialled another option. Here's a link to the commit (not fully done, but has the gist of it). So, this works, pretty well actually, but the only slight disadvantage is that storybook would be `~/../storybook`. I'm okay with that, and you can watch today's stream (first section) to see why. But interested in getting your thoughts, too.

https://github.com/jamonholmgren/FastingApp/commit/ff1c35d6eaef425e880dc9bb77ee442a6adf9163

**Comment by flexbox** [comment]
Just tried the `tsconfig.json` strategy only on another project.
https://github.com/flexbox/react-native-bootcamp/pull/77/commits/1d0df58a531583558ee82035fe61328053bd374b

It works fine, and avoid having a dependency with `babel-plugin-root-import`.
This is a better solution to reduce errors due to the plumbing 😅 

Next step:
I will investigate the storybook issue on `ignite-cli`

**Comment by flexbox** [comment]
Just noticed with the `package.json` approach, during expo build, we are running into an error

image


Next step:

- [ ] try to build the project
- [ ] investigate the storybook issue on ignite-cli

**Comment by flexbox** [comment]
Closing that for now because

I don't have the bandwidth right now
let the team focus on https://github.com/infinitered/ignite/milestone/19

**Pull request closed without merging**
