### PR TITLE
Detect version update

### LINKED ISSUE #240: [GEN | CLI] - Detect version updates
It just hit me that people on old versions of ignite will be like "WHAAAAAAAT?"

We should build it in now that if your'e running X and Y comes out, it should give a friendly message.  ASCII art is a must!

### PR DESCRIPTION
**Pull request by pradel**
## Please verify the following:
- [x] Everything works on iOS/Android
- [x] `ignite-base` **ava** tests pass
- [x] `fireDrill.sh` passed

## Describe your PR
Cli now automatically detect version updates.
With  [update-notifier](https://github.com/yeoman/update-notifier).
Close #240

### CODE REVIEW

**Comment by GantMan** [comment]
Have you found a good way to test this?  I pulled your branch down and I've lowered the version number and ran `ignite doctor` expecting it to alert me. But alas, it does not.

image

### Any way to test?

**Comment by pradel** [comment]
Have you already tried the command before changing the package version ? If yes there is a cache in update notifier, it will check for an update and if no updates found it will only recheck on npm 24 hours after (https://github.com/yeoman/update-notifier#updatecheckinterval).

You can disable cache by comenting L84 to 86 in node_modules/update-notifier/inde.js

capture d ecran 2016-09-02 a 16 33 44

**Comment by skellock** [comment]
This might be wrong @GantMan, but you're not `npm link`'ing your Ignite are ya?

Also,  wtf is up with your console font?

image

**Comment by pradel** [comment]
Also doctor take the global installed version of ignite and update-notifier will take the version of you local package.json so you don't need to have your global ignite lowered.
As you can see on the picture I posted upper I have a gloabl 1.6.1 ignite version but I put ignite to 1.5.2 in my local package.json.

**Comment by GantMan** [comment]
LGTM!  👍 

And @skellock - it's called "Big ol head" font.   Ok, not really.

**Pull request merged**
