### PR TITLE
chore: migrate to new react-native-async storage package

### PR DESCRIPTION
**Pull request by harrisrobin**
## Please verify the following:

- [x] `yarn ci:test` **jest** tests pass with new tests, if relevant
- [x] `README.md` has been updated with your changes, if relevant

## Describe your PR
`react-native-async-storage` has moved away from `react-native-community` and into it's own organization, so we are currently pointing to a deprecated package. This PR updates all references to react-native-async-storage to use the new location at https://github.com/react-native-async-storage/async-storage. There are no breaking changes from my testing.

### CODE REVIEW

**Comment by yulolimum** [comment]
@harrisrobin just a though but since we have `unimodules` integrates - we could just use: https://docs.expo.io/versions/v40.0.0/sdk/async-storage/

**Comment by harrisrobin** [comment]
> @harrisrobin just a though but since we have `unimodules` integrated - we could just use: https://docs.expo.io/versions/v40.0.0/sdk/async-storage/

I like that idea. will look into it tomorrow

**Review by jamonholmgren — APPROVED** [review]
Nice!

**Review by jamonholmgren — CHANGES_REQUESTED** [review]
Actually I like the idea of using the Expo unimodule, since that will work on Expo as well.

**Comment by harrisrobin** [comment]
@yulolimum @jamonholmgren after looking at this again, seems like Expo simply points to `@react-native-async-storage/async-storage` so I believe there is nothing else to do here 😄

**Pull request merged**
