### PR TITLE
feat(cli): adds expo-canary and expo-beta cli opts

### PR DESCRIPTION
**Pull request by frankcalise**
## Describe your PR
- Adds ability for a user to utilize the Beta or Canary release of Expo via the dist-tags at npm
- Mostly interested in trying out the new Debugger experience
- Plans on using this for CI uses especially, to find bugs ahead of time with future releases
- Pretty much the equivalent of taking an existing Ignite / Expo project and doing the following:
```
bun install expo@canary
npx expo install --fix
npx expo prebuild --clean
```

## Notes
- Probably should refactor the experimental flags code since we'd end up writing this block to parse the flag for each new one we decide to add

## Test Locally
- Checkout the branch
- Run:
```
yarn build
cd ..
ignite/bin/ignite new ignite-canary-cli --debug --install-deps=true --packager=bun --overwrite --remove-demo --workflow=prebuild --experimental=expo-canary --yes 
```

## Details
- Adds `--experimental=expo-canary` or `--experimental=expo-beta` cli flag (can be combined with new architecture, ie: `--experimental=expo-canary,new-arch`
- Finds latest Expo Beta or Canary version published to NPM and switches the dependency in `package.json`
- After dependency install, runs `npx expo install --fix` to get the proper set of Expo supporting dependency beta/canary versions
  - > Note: `npx expo install --fix` doesn't install ALL deps, just the expo ones, so had to run this in addition to the packager install
- Appends `expo-font` to `app.json` plugins (this is temporary, once SDK 50 is released this will just be updated in the boilerplate)

## Screenshots
image

image

image

### CODE REVIEW

**Review by jamonholmgren — APPROVED** [review]
Very nice. Do we need to document it anywhere in the repo? Probably need to document the whole `--experimental=` options here or somewhere like it.

https://github.com/infinitered/ignite/blob/master/docs/Ignite-CLI.md#options-1

**Comment by frankcalise** [comment]
> Very nice. Do we need to document it anywhere in the repo? Probably need to document the whole `--experimental=` options here or somewhere like it.
> 
> https://github.com/infinitered/ignite/blob/master/docs/Ignite-CLI.md#options-1

This will be taken care of in Monday's super secret release

image

**Comment by jamonholmgren** [comment]
@frankcalise Perfect!

**Pull request merged**
