### PR TITLE
Update Generators.md documentation

### PR DESCRIPTION
**Pull request by jsflor**
Change all "ignite" commands to "ignite-cli"

## Please verify the following:

- [x] `yarn ci:test` **jest** tests pass with new tests, if relevant
- [x] `README.md` has been updated with your changes, if relevant

### CODE REVIEW

**Comment by nirre7** [comment]
Thank you for helping us keeping the docs up to date!
I think it is even better if we add the `npx` i.e `npx ignite-cli generate component MyNewComponent`.
That way we might get less environment related issues 🤞

**Review by jamonholmgren — APPROVED** [review]
Ooh, good catch.

I agree with @nirre7 about the npx additions, but those can be a separate PR.

**Comment by jsflor** [comment]
Absolutely @nirre7! @jamonholmgren let me handle this! 😄

**Pull request merged**
