### PR TITLE
Only list commands available in directory

### LINKED ISSUE #845: Pare down the ignite commands to what is feasible.
Currently I can be in any folder and type `ignite` and I'll see every option.
image

Technically some of these are not proper for a user, but they must be typed find that out.   
image

^ see?  The very first command listed and **RED TEXT**.   An experienced Ignite user knows... but a non-experienced ignite user immediately gets nada!

So my suggestion is, when you're in an empty folder you get:
```
  doctor         Checks your dev environment for dependencies.
  new (n)        Generate a new React Native project with Ignite.
  plugin (p)     Manages ignite plugins
  version (v)    Prints current version of installed ignite
```
🌅  Ahhhh, so clean, so friendly.

and when you're in an Ignite project, you get:
```
  add (a)        Adds an Ignite plugin.
  doctor         Checks your dev environment for dependencies.
  generate (g)   Generates some files.
  plugin (p)     Manages ignite plugins
  remove (r)     Removes an Ignite plugin.
  spork          Copy templates as blueprints for this project
  version (v)    Prints current version of installed ignite
```
w00t!  What a great set of options that all make sense!

### PR DESCRIPTION
**Pull request by morgandonze**
## Please verify the following:

- [x] Everything works on iOS/Android
- [x] `yarn ci:test` **jest** tests pass with new tests, if relevant
- [x] `./docs/` has been updated with your changes, if relevant

## Describe your PR
Fixes #845
I have the desired commands showing in ignited and non-ignited dirs:

Screen Shot 2020-02-11 at 3 02 30 PM
(I deleted `ignite.json` to simulate a non-ignite directory`)

### CODE REVIEW

**Comment by jamonholmgren** [comment]
This looks quite good, @mlaco ! 

I'd like to potentially move the logic into the meta extension rather than in the command. But I haven't thought through what that would look like. Any ideas?

**Comment by mlaco** [comment]
I'll think about it and get back to you

**Comment by bryanstearns** [comment]
@jamonholmgren CI passing now; the Bowser component generator now asks a question by default, so the test needed to pass an answer; an assertion needed updating too.

**Pull request merged**
