### PR TITLE
Add cookbook link to main Ignite README

### PR DESCRIPTION
**Pull request by robinheinze**
## Please verify the following:

- [ ] `yarn test` **jest** tests pass with new tests, if relevant
- [x] `README.md` has been updated with your changes, if relevant

## Describe your PR

- Add a link over to Ignite Cookbook (🎉 ) from the README

### CODE REVIEW

**Review by frankcalise — APPROVED** [review]
Let's goooooo 🚀

**Comment by markrickert** [comment]
Should CI be checking the prettier format of markdown files?

Screenshot 2023-02-02 at 11 59 05 AM

**Comment by robinheinze** [comment]
@markrickert I think it's ok. I did this one in the GH editor so prettier didn't run like it would locally, so normally it would be fine.

**Comment by frankcalise** [comment]
> @markrickert I think it's ok. I did this one in the GH editor so prettier didn't run like it would locally, so normally it would be fine.

I think next time you can include `[skip ci]` in the squash commit body or commit message `docs: Updated readme` so that we don't publish this as a new version in this case.

**Comment by robinheinze** [comment]
Yep, I always forget that 🤦‍♀️ I cancelled the workflow this time. It might run the next time a PR is merged but hopefully that will be for actual changes so it won't matter.

**Pull request merged**
