### PR TITLE
fix: update `Generators` reference

### PR DESCRIPTION
**Pull request by emmanuel-ferdman**
## Please verify the following:

- [ ] `yarn test` **jest** tests pass with new tests, if relevant
- [ ] `yarn lint` **eslint** checks pass with new code, if relevant
- [ ] `yarn format:check` **prettier** checks pass with new code, if relevant
- [ ] `README.md` (or relevant documentation) has been updated with your changes
- [ ] If this affects functionality there aren't tests for, I manually tested it, including by generating a new app locally if needed ([see docs](https://docs.infinite.red/ignite-cli/contributing/Contributing-To-Ignite/#testing-changes-from-your-local-copy-of-ignite)).

## Describe your PR

Commit 26614c54bb1ba865119c0516ac314a5603f9715c moved the `Generators.md` file to `concept` directory. This PR adjusts sources to changes.

## Screenshots (if applicable)

| Before                           | After                           |
| -------------------------------- | ------------------------------- |
| [Insert before screenshot/video] | [Insert after screenshot/video] |

### CODE REVIEW

**Review by frankcalise — CHANGES_REQUESTED** [review]
Hey thanks for the contribution and great find!

Let's update it to this link actually where the docs are hosted if you don't mind.

https://docs.infinite.red/ignite-cli/concept/Generators/

**Comment by emmanuel-ferdman** [comment]
@frankcalise thank you for the review, I updated the PR

**Review by frankcalise — APPROVED** [review]
Thanks!

**Pull request merged**
