### PR TITLE
Update generators to include barrel exports automatically

### PR DESCRIPTION
**Pull request by kateinkim**
Addresses: #1609 and #1610 

Updates `generateFromTemplate` to append an index file if it exists and the file is one likely to want exporting 😉 

Assumptions made:
* Index file is ts, tsx, js, or jsx and should include exports
* Files including `.test` or `.story` shouldn't be included in exports (could there be others?)

### CODE REVIEW

**Comment by jamonholmgren** [comment]
This is awesome.

3 things:

1. Could we have an option for skipping this? `--skip-index-file` comes to mind, but other ideas welcome
2. Any documentation need to be updated for this?
3. Any tests could be updated for this? [Here's a good candidate](https://github.com/infinitered/ignite/blob/8cbcfd6e58f918c3ff477d2e6bec147725b1b645/test/ignite-new.test.ts#L95-L102)

**Comment by kateinkim** [comment]
Thanks Jamon!

1. I added the skip option. I liked your name.
2. I just updated one line in the docs. Not sure if there's something else I should add.
3. I updated that test to check for the appended export but the test seems to hang so I can't verify if it's passing. Any ideas?

**Comment by jamonholmgren** [comment]
Current CI failure is related to https://github.com/infinitered/solidarity/issues/263.

**Comment by jamonholmgren** [comment]
I'm not entirely sure what the latest test failure is, tbh.

**Comment by kateinkim** [comment]
@jamonholmgren I figured it out. Just needed to configure the user for git before the test runs. Apparently circle doesn't have a git user setup by default. Tests are passing now!

High five

**Comment by jamonholmgren** [comment]
Yay!! Thanks @kateinkim . I'll release this soon.

**Pull request merged**
