### PR TITLE
Upgrade/0.32.0

### PR DESCRIPTION
**Pull request by GantMan**
## Please verify the following:
- [x] Everything works on iOS/Android
- [x] `ignite-base` **ava** tests pass
- [x] `fireDrill.sh` passed

## Describe your PR

# Upgrades manny packages, all are awesome.

### CODE REVIEW

**Comment by GantMan** [comment]
@kevinvangelder  @ryanlntn  -  Quick review and merge would be awesome.

**Comment by GantMan** [comment]
This will close #319

**Comment by GantMan** [comment]
image

**Comment by skellock** [comment]
I dig it.  I, too, am an avid self-mergist.

**Comment by ryanlntn** [comment]
Approved post hoc! 👍

**Comment by GantMan** [comment]
I award @ryanlntn one internet star ⭐  for his latin.

**Comment by ryanlntn** [comment]
Gratias tibi ago!

**Comment by skellock** [comment]
image

**Pull request merged**
