### PR TITLE
using nyc html reporter instead of text

### PR DESCRIPTION
**Pull request by hiaw**
## Please verify the following:
- [x] Everything works on iOS/Android
- [x] `ignite-base` **ava** tests pass
- [x] `fireDrill.sh` passed

## Describe your PR

Using the html reporter for nyc coverage.

### CODE REVIEW

**Comment by GantMan** [comment]
I like this idea.   Couple things.   1, we should have a nice option to run in terminal too.  Maybe `npm run cov` in classic *NIX shortcut, OR, perhaps it prints to the console AND does the HTML?  Thoughts @skellock ?

The second issue, is a bit more substantial.   If you don't have the folder created, this errors.  So first time users will see errors. 
image

Actually, it looks like nyc ava report --reporter=html doesn't generate latest output, just converts last output to HTML.  Thoughts?

**Comment by hiaw** [comment]
Sorry I didn't check for first use. Now it should work first time. It will also give both text and html output. 

As for terminal, it should work `npm run coverage`

**Comment by skellock** [comment]
Not at my computer, so cant verify, but I'm behind this if the html report is awesome!  Thanks!

**Comment by GantMan** [comment]
@hiaw  - works great!

**Comment by hiaw** [comment]
if you just type `npm run coverage` into the terminal then should work

**Pull request merged**
