### PR TITLE
Ignite v8: Maverick

### PR DESCRIPTION
**Pull request by jamonholmgren**
This will be the draft PR for Ignite v8, code-named Maverick.

Milestone (more info here): https://github.com/infinitered/ignite/milestone/19

### CODE REVIEW

**Review by flexbox — APPROVED** [review]
Tom approves!

image

**Review by joshuayoes — APPROVED** [review]
Ready for launch 😎

**Review by frankcalise — APPROVED** [review]

**Review by robinheinze — APPROVED** [review]
💯

**Pull request merged**
