### PR TITLE
Upgrade to RN 0.37

### PR DESCRIPTION
**Pull request by ryanlntn**
## Please verify the following:
- [x] Everything works on iOS
- [ ]  Everything works on Android
- [x] `ignite-base` **ava** tests pass
- [x] `fireDrill.sh` passed

## Describe your PR
Addresses https://github.com/infinitered/ignite/issues/485

I wasn't able to check Android because maps failed due to not finding the right version of play services. I think that might just be an issue with the SDK version I have installed though. 

Also it looks like a bunch of the ignores I added to .flowconfig were removed so flow kind of blows up when you run fireDrill.sh. It still passes though ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by GantMan** [comment]
@ryanlntn - Can you please update/verify Android?

Also, let's make fireDrill fail on flow fail.  It makes sense right?   Who removed your ignores?

**Comment by ryanlntn** [comment]
Apparently I did lol. I'll get this finished up today.

**Comment by ryanlntn** [comment]
Interesting. Flow is passing for me locally but getting loads of required module not found errors on Semaphore. Not sure why that would be...

Also this is super annoying: https://github.com/facebook/flow/issues/869

I really wish we could just ignore all errors with node_modules.

**Comment by ryanlntn** [comment]
@GantMan Still not able to run this on Android. Looks like maps is broken again: `Could not find com.google.android.gms:play-services-base:9.4.0.`

**Comment by GantMan** [comment]
@ryanlntn - you can shell into semaphore, which is cool.   That way you can have a socket5 webterm to the actual instance, and play around on the actual box.

Also, that's crazy about the 9.4.0 stuff.  But especially since I added code that undoes 9.4.0 locking.  Perhaps we can pair sometime and identify the issue so we will be down to document/fix for someone who hits this problem.

**Comment by robbue** [comment]
We are depended on react-native-router-flux to update using the NavigationExperimental to leverage the new changes provided in RN 0.37?

**Comment by GantMan** [comment]
@robbue - I'm not sure.  I haven't tried yet.  Quite likely, yes.  Though you can always wire that up yourself and not wait.

**Comment by ryanlntn** [comment]
@GantMan I've resolved the issues with fireDrill.sh. Looks like node modules weren't actually getting installed before flow check on Semaphore. The only issue now is that I still get build failures on Android due to react-native-maps looking play services to 9.4.0. The code you have for overriding that doesn't appear to work.

**Comment by GantMan** [comment]
did you also take care of this one?   https://github.com/infinitered/ignite/issues/484

If not, I will take a look.

**Comment by GantMan** [comment]
@ryanlntn - Looks great bud!

I did some library upgrades too.  This PR is ready as soon as it passes CI

**Pull request merged**
