### PR TITLE
Re-order plugins and added native-navigation plugin

### PR DESCRIPTION
**Pull request by adrienthiery**
## Please verify the following:
- [x] `./docs/` has been updated with your changes, if relevant

## Describe your PR

* Re-ordering plugins alphabetically
* Adding native-navigation plugin

### CODE REVIEW

**Comment by juddey** [comment]
Just wondering if this could be merged? I have some more plugins to add but want to avoid merge conflict. Cheers.

**Comment by GantMan** [comment]
MERGED!  Also... @adrienthiery and @juddey any interest in being maintainers?  I don't have as much time lately and I trust you two.

**Comment by adrienthiery** [comment]
@gantman sure!

**Comment by GantMan** [comment]
@adrienthiery and @juddey - welcome to Ignite core contributors!!!

**Comment by adrienthiery** [comment]
Isn't that a spiderman quote? 😂

**Comment by juddey** [comment]
Not sure. Aunty Google told me it was the green man, and I believe her.

**Pull request merged**
