### PR TITLE
fix(cli): fixed frontmatter clean up in generate cmd

### LINKED ISSUE #2325: ignite-cli generate command leaves some unnecessary lines
### Describe the bug

When I try to run `npx ignite-cli generate model MODEL_NAME`, the resulted file still contains some additional lines inherented from the .ejs template files like so:
image

### Ignite version

8.4.2

### Additional info
```
System
  platform           win32       
  arch               x64         
  cpu                8 cores      Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
  directory          IgniteApp    C:\Users\mh\Desktop\Codes\_sketch\IgniteApp

JavaScript (and globally-installed packages)
  node                    16.14.0                                   C:\Program Files\nodejs\node.EXE
  npm                     8.3.1                                     C:\Program Files\nodejs\npm.CMD
    expo-cli              6.0.8                                    
  yarn                    1.22.15                                   C:\Program Files\nodejs\yarn.CMD                       
    create-vite           3.1.0                                    
    docsify-cli           4.4.4                                    
    expo-cli              6.0.8                                    
    react-native          0.70.2                                   
    turtle-cli            0.28.1                                   
  pnpm                    6.11.0                                    C:\Program Files\nodejs\pnpm.CMD
                          <no pnpm global package info available>  
  expo                    46.0.17                                   managed

Ignite
  ignite-cli         8.4.2        C:\Users\mh\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\.bin\ignite.CMD
  ignite src         build        C:\Users\mh\AppData\Local\npm-cache\_npx\e31027f3785124a8\node_modules\ignite-cli\build

Android
  java               11.0.13      C:\Program Files\Eclipse Adoptium\jdk-11.0.13.8-hotspot\bin\java.EXE
  android home       -            C:\Users\mh\AppData\Local\Android\Sdk

Tools
  git                git version 2.32.0.windows.2   C:\Program Files\Git\cmd\git.EXE 
```

### PR DESCRIPTION
**Pull request by frankcalise**
## Please verify the following:

- [x] `yarn test` **jest** tests pass with new tests, if relevant
- [x] `README.md` has been updated with your changes, if relevant

## Describe your PR
- Closes #2325

### CODE REVIEW

**Comment by frankcalise** [comment]
@joshuayoes if you could review and test win/mac via npm link it would be appreciated :)

I ran through it but to double check

**Comment by joshuayoes** [comment]
> @joshuayoes if you could review and test win/mac via npm link it would be appreciated :)
> 
> I ran through it but to double check

Yeah I can take a look at this tomorrow!

**Review by joshuayoes — APPROVED** [review]
I tried it on Windows, and it still had the same issue. Gluegun has a utility for end-of-line that I added, which I tested on Windows and Mac and seems to be working

**Comment by frankcalise** [comment]
> I tried it on Windows, and it still had the same issue. Gluegun has a utility for end-of-line that I added, which I tested on Windows and Mac and seems to be working

Nice! yeah it looks like I committed a typo even, not sure why `"n"` was there, should have been empty quotes. I like your EOL fix though. Thanks!

**Comment by frankcalise** [comment]
@joshuayoes actually I still see the same issue, what shell are you running in Windows?

This is the only thing that I've seen working:
`const NEW_LINE = process.platform === "win32" ? "" : "\n"`

**Comment by joshuayoes** [comment]
I was running bash on windows, which may be giving me a false positive. I'll try again with powershell and cmd

**Comment by joshuayoes** [comment]
To link the CLI, I ran
```
yarn install
yarn build
npx link
```

And then to test, I ran
```
cd boilerplate
npx ignite-cli generate component Checkbox
```
On bash, powershell, and cmd on windows. I'm seeing the EOL fix working in all those shells on my machine

**Pull request merged**
