### PR TITLE
Use internal StyleSheet.flatten instead ramda

### PR DESCRIPTION
**Pull request by pronevich**

### CODE REVIEW

**Review by jamonholmgren — APPROVED** [review]
Nice! This will work well. Thanks @pronevich !

**Comment by pronevich** [comment]
Yeah, I made PR early today) #1685

**Comment by pronevich** [comment]
Also, before PR I have checked that RN styles will flatten for any nesting level.

**Comment by jamonholmgren** [comment]
That's awesome! Thanks @pronevich !

**Pull request merged**
