### PR TITLE
feat(boilerplate): Make texts on demo components based on i18n

### PR DESCRIPTION
**Pull request by kei95**
## Please verify the following:

- [x] `yarn test` **jest** tests pass with new tests, if relevant
- [x] `yarn lint` **eslint** checks pass with new code, if relevant
- [x] `yarn format:check` **prettier** checks pass with new code, if relevant
- [x] `README.md` (or relevant documentation) has been updated with your changes

## Describe your PR
This is a follow-up PR to cover *all* demo components under `DemoShowroomScreen/` with i18n file. Since demos were not covered by it, [my previous translation PR](https://github.com/infinitered/ignite/pull/2709) couldn't translate all the essential parts of the boilerplate. 

@mazenchami has [suggested me](https://github.com/infinitered/ignite/pull/2709#issuecomment-2242973423) create demo files to adopt i18n in demo components (thanks for the guide!) so I made the change in this PR along with translations provided by @flexbox and @leonskim 🎉 

## recording
https://github.com/user-attachments/assets/5720a743-578d-4da4-8d07-7dae26e69f6c

### CODE REVIEW

**Review by flexbox — APPROVED** [review]
Sounds Good To Me 🚀 

Do not merge it before @mazenchami translate the file `demo-ar.ts`

**Comment by kei95** [comment]
> @kei95 very sorry for the delay on this but here is the code for the demo-ar.ts file. once you've uploaded it, i'll do a final pass and we can merge the PR:

No problem at all! I just applied the the change so please have a look when you get a chance

**Comment by kei95** [comment]
@mazenchami It appears to be your demo-ar.ts is missing `description` property under `demoListItem/useCase/icons`. Would you like to translate the text below so that I can add quickly? 👀  

original `description: "You can customize the icons on the left or right."`

Screenshot 2024-08-13 at 2 49 04 PM

**Comment by mazenchami** [comment]
@kei95 great catch. here it is: "يمكنك تخصيص الرموز على اليسار أو اليمين"

**Comment by kei95** [comment]
@mazenchami All tests are passing now and I believe it should be good to go now!

**Comment by mazenchami** [comment]
@kei95 sorry for the delay but merging this now. thanks for all your work on making this possible!

**Pull request merged**
