### PR TITLE
enhancement(cli) : add overwrite option when using generate command

### PR DESCRIPTION
**Pull request by aymane-missouri-nw**
## Please verify the following:

- [x] `yarn test` **jest** tests pass with new tests, if relevant
- [ ] `README.md` has been updated with your changes, if relevant

## Describe your PR
 - For this issue https://github.com/infinitered/ignite/issues/2354
 - Add possibility to overwrite or not files when using command generate
 - Don't remove files that exists when using command generate  unless they specifiy the property --overwrite in it.

### CODE REVIEW

**Comment by frankcalise** [comment]
@aymane-missouri-nw thanks for the contribution - could you please update the existing test to account for the new output and add a test case for the overwrite mechanism?

**Comment by aymane-missouri-nw** [comment]
@frankcalise  I created tests for the overwrite mechanism and the tests passes locally but in pipelines they fail other tests , any thoughts ?

**Comment by frankcalise** [comment]
Ok we'll look into it, thanks

**Comment by aymane-missouri-nw** [comment]
@frankcalise I just update the branch with current master and test passes now

**Comment by frankcalise** [comment]
@aymane-missouri-nw this looks great!

One improvement I'm wondering if we can try to address, let me know your thoughts.

When a file does exist and the overwritten flag is not passed (so for example, the Screen file doesn't get written), can we avoid any further patches being applied? Does it make sense to do this?

The patch to the `index.ts` files really doesn't have to occur again, not sure we can make that smarter. Or if we should assume that the export is there? Since the file exists, likely that export exists too, so we shouldn't end up with

**app/screens/index.ts**

```tsx
export * from "./OtherScreen"
export * from "./ExistingScreen"
export * from "./ExistingScreen"
```

**Comment by aymane-missouri-nw** [comment]
@frankcalise  you're right i forgot this edge case , i will adress it and i think we should assume that the export is there because the file is already exist

**Comment by aymane-missouri-nw** [comment]
@frankcalise i pushed a commit for handling patch , let me know your thoughts

**Comment by aymane-missouri-nw** [comment]
@frankcalise i have handle this case , can u recheck and give me your thoughts ?

**Comment by TheMissouri** [comment]
@frankcalise any news ?

**Pull request merged**
