### PR TITLE
Sets locale dynamically if system uses a regional language

### PR DESCRIPTION
**Pull request by sergioisidoro**
See https://github.com/infinitered/ignite/issues/2414

### CODE REVIEW

**Comment by sergioisidoro** [comment]
Tests are failing. Not sure how to proceed here :)

**Comment by flexbox** [comment]
@sergioisidoro 
have you tried to update the snapshot with
```
yarn test -u
```

**Comment by frankcalise** [comment]
Thanks for the contribution but we are not looking to pull this into Ignite at this time. I believe if we changed languages from LTR to RTL it wouldn't be reflected still.

**Comment by markrickert** [comment]
Hey @sergioisidoro, there's been a few changes in the `i18n` file and there are some conflicts in your PR now. Could you rebase on `master` and see if these changes are still necessary

**Review by mazenchami — APPROVED** [review]
Great work on this @sergioisidoro. I just resolved conflicts and will merge now!

**Comment by mazenchami** [comment]
@sergioisidoro thanks for inspriation on this! I had to make a couple other changes, so take a look at this #2611 which will close out your issue!

**Pull request closed without merging**
