### PR TITLE
Replaced withRootStore extension with getRootStore helper

### PR DESCRIPTION
**Pull request by frankcalise**
## Please verify the following:

- [ ] `yarn ci:test` **jest** tests pass with new tests, if relevant
- [ ] `README.md` has been updated with your changes, if relevant

## Describe your PR

As per #1974, removed `withRootStore` extension in favor of `getRootStore` helper function. Also updated the `Folder Structure` documentation to reflect the new changes

image

### CODE REVIEW

**Review by mazenchami — COMMENTED** [review]
@frankcalise great work on this.

Can you please update the docs to also reflect this change? `/docs/Folder-Structure.md` line 70 still references `withRootStore`. Thank you!

**Comment by frankcalise** [comment]
> @frankcalise great work on this.
> 
> Can you please update the docs to also reflect this change? `/docs/Folder-Structure.md` line 70 still references `withRootStore`. Thank you!

Oops, didn't push my last commit up! Need more ☕ Doc updates should be there now :)

Feel free to suggest different wording.

**Review by mazenchami — APPROVED** [review]
Looks good to me!

**Review by jamonholmgren — APPROVED** [review]
lgtm -- @mazenchami feel free to release at your convenience. Can bundle with other features with [skip ci] if you want, as it's a relatively small change.

**Comment by midrizi** [comment]
Issue still persists. I cloned the repo in master branch and tested this.

| another-store.ts  | root-store.ts |
| ------------- | ------------- |
|   |   |

**Comment by midrizi** [comment]
Upon further investigation for some reason adding `action((self) => ...)` to the second store breaks types. If `action` is not present in the second store, works as expected. But why does `characterStore` work and second store doesn't?

**Comment by midrizi** [comment]
Working without action:

Screenshot from 2022-07-14 15-41-13

Screenshot from 2022-07-14 15-41-22

**Pull request merged**
