### PR TITLE
[Base] - Add fastlane

### PR DESCRIPTION
**Pull request by GantMan**
#### Ignite Base Change
- [x] Works on iOS/Android/XDE
- [x] Tests Pass (run: `npm run test`)
- [x] Code is StandardJS compliant (run: `npm run lint`)

fastlane template code.  Should remove the need for anyone to `fastlane init`

### CODE REVIEW

**Comment by GantMan** [comment]
This PR closes #64

**Comment by ahmed1490** [comment]
is this removed from the project?

**Comment by ahmed1490** [comment]
I dont see fastlane folder in the generated project

**Comment by GantMan** [comment]
o wow, that's probably our mistake when we made the generator.   Another great catch!  Will fix right away.  For existing projects, just copy the fastlane folder over from `ignite-base`

**Comment by GantMan** [comment]
@ahmed1490  ->  https://github.com/infinitered/ignite/pull/216

**Pull request merged**
