### PR TITLE
Add ignite-cli binary command

### PR DESCRIPTION
**Pull request by anusha5695**
**Issue:**
This PR is linked to the issue: https://github.com/infinitered/ignite/issues/1487

**Summary of changes:**
Added a new file for ignite-cli under bin that refers ignite

### CODE REVIEW

**Comment by jamonholmgren** [comment]
@anusha5695 Thanks for doing this! Did you happen to chmod the binary so it's executable? I also forgot to ask you to add it to the package.json: https://github.com/infinitered/ignite/blob/8c780339ffa0c7b2626b381d492bfd40dfc826d0/package.json#L5-L7

**Comment by anusha5695** [comment]
Yes i did do chmod. And will add it to package.json 👍

**Comment by jamonholmgren** [comment]
@anusha5695 This makes me think maybe we don't even need the other binary? Just this?

```
 "bin": { 
   "ignite": "bin/ignite",
   "ignite-cli": "bin/ignite" 
 }, 
```

**Comment by anusha5695** [comment]
@jamonholmgren : If thats the case would we even need a second command. We could link ignite with npx as well?

**Comment by jamonholmgren** [comment]
@anusha5695 I agree, we wouldn't need the second command. We do need to make sure `ignite` and `ignite-cli` point to the same binary.

**Comment by ahmdsolmn** [comment]
@jamonholmgren @anusha5695 Any updates here ?

**Pull request merged**
