### PR TITLE
Relocates to infinitered/ignite-ir-boilerplate-2016.

### PR DESCRIPTION
**Pull request by skellock**
[And up we go!](https://www.youtube.com/watch?v=n95A6G9IxlM)

### CODE REVIEW

**Comment by jamonholmgren** [comment]
https://github.com/infinitered/ignite-ir-boilerplate-2016

**Comment by jamonholmgren** [comment]
Need this on npm before we can merge, right?

**Comment by skellock** [comment]
You can add this path to your IGNITE_PLUGIN_PATH, but ya, we can push it!  I'm just getting the plugin script in place now.

**Comment by skellock** [comment]
published.

**Pull request merged**
