### PR TITLE
Fix expo-cli hermes sanity checks on publish

### PR DESCRIPTION
**Pull request by sergioisidoro**
## Please verify the following:

- [x] `yarn test` **jest** tests pass with new tests, if relevant
- [x] `README.md` has been updated with your changes, if relevant

## Describe your PR
I was trying to publish the app with expo new EAS, and was hitting this issue:
```
sergio@leviathan MyAppProject % yarn eas update                                                                                                                                                                   [4/10/22 | 11:32:44]
yarn run v1.22.11
warning ../package.json: No license field
$ /Users/sergio/Developer/MyAppProject/node_modules/.bin/eas update
Found eas-cli in your project dependencies.
It's recommended to use the "cli.version" field in eas.json to enforce the eas-cli version for your project.
Learn more: https://github.com/expo/eas-cli#enforcing-eas-cli-version-for-your-project

Found eas-cli in your project dependencies.
It's recommended to use the "cli.version" field in eas.json to enforce the eas-cli version for your project.
Learn more: https://github.com/expo/eas-cli#enforcing-eas-cli-version-for-your-project

✔ No branches found. Provide a branch name: … main
✔ Provide an update message. … App boilerplate

[expo-cli] --non-interactive is not supported, use $CI=1 instead
[expo-cli] Error: JavaScript engine configuration is inconsistent between app.json and iOS native project.
[expo-cli] In app.json: Hermes is enabled
[expo-cli] In iOS native project: Hermes is not enabled
[expo-cli] Please check the following files for inconsistencies:
[expo-cli]   - /Users/sergio/Developer/MyAppProject/app.json
[expo-cli]   - /Users/sergio/Developer/MyAppProject/ios/Podfile
[expo-cli]   - /Users/sergio/Developer/MyAppProject/ios/Podfile.properties.json
[expo-cli] Learn more: https://expo.fyi/hermes-ios-config
[expo-cli] Error: JavaScript engine configuration is inconsistent between app.json and iOS native project.
[expo-cli] In app.json: Hermes is enabled
[expo-cli] In iOS native project: Hermes is not enabled
[expo-cli] Please check the following files for inconsistencies:
[expo-cli]   - /Users/sergio/Developer/MyAppProject/app.json
[expo-cli]   - /Users/sergio/Developer/MyAppProject/ios/Podfile
[expo-cli]   - /Users/sergio/Developer/MyAppProject/ios/Podfile.properties.json
[expo-cli] Learn more: https://expo.fyi/hermes-ios-config
```

After checking the code generating these, it seems that they are checking both the Podfile and `boilerplate/ios/Podfile.properties.json`, as well as `gradle.properties` 

It seems this package is using hermes by default, so I think this would be useful for others.  

_Edit: added full command and trace for reference_

### CODE REVIEW

**Comment by frankcalise** [comment]
Hmm that's interesting, because the RN notes say nothing about those flags: https://reactnative.dev/docs/hermes

@sergioisidoro are you doing an Expo build and don't need the android/ios directories? Does this occur if you were to delete those and run a build?

**Comment by sergioisidoro** [comment]
Unfortunately these are not react-native flags, but something that seems to be baked into expo-cli, which are checked via not so reliable regex expressions:

https://github.com/expo/expo-cli/pull/4382
https://github.com/expo/expo-cli/issues/4283

**Comment by sergioisidoro** [comment]
Ok, indeed some of these checks are a bit confusing, between expo build and bare workflow. I was aiming for a Expo build, but somehow I ended up triggering a bare workflow build

However the new EAS does allow building apps with bare workflow, so that Expo is the CI for building the apps, so this information might be useful for someone. 

I guess we can close this one :)

**Comment by frankcalise** [comment]
Hmm I'll review them, they might be needed actually and have no impact on a bare project. Think they're just indicators for EAS builds which we would want to support.

**Comment by sergioisidoro** [comment]
I reopened it then. As a navigation warning: 

If you don't use eas, everything is ok, and you can use expo and develop things with the managed workflow even tho there are ios and android folders. You can even use the old `expo publish`.

However, as soon as you do `eas update:config` and `eas build:configure`, it will assume a managed workflow if there are `ios` and `android` folders, adding a `runtimeVersion` config to `app.json`. **EAS does not support policy SDK version in the runtimeVersion in bare workflow**

This will result in expo assuming managed workflow, and it will completely break expo. Expo go will no longer work in the dev environment, showing a "SDK not supported error".

I will still need some time to understand the difference in the build process between `expo publish` and `eas update`.

The good news is, with this PR, eas builds work almost out of the box.
We just need configure it and it just works.

**Comment by frankcalise** [comment]
Thanks for the excellent explanation - and I know we want to support EAS builds out of the box. If there is no side effect to regular  react-native builds (bare workflow, android/ios dirs involved) then that would be great. Just want to do some testing around that.

**Comment by frankcalise** [comment]
Yeah I think I'm good with this. The Expo run:ios / run:android commands add this in anyway to the native code, so I don't think it'll interfere at all. Thanks for the contribution!

**Pull request merged**
