### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by GantMan**
adding integration tests to CI

### CODE REVIEW

**Comment by skellock** [comment]
I'm more in favour of using `ava` to test this stuff, but bash is fine. The important thing is that it's works.  

Since we're testing the ignite boilerplate, thoughts of moving this there?

Also, may as well delete `packages/ignite-integration-tests` now that we've switched to shell-based testing.

**Comment by GantMan** [comment]
@skellock - let's talk about this.  I might have taken us backwards in time.  Since we did not have any e2e integration tests, I added this.  Are you saying `packages/ignite-integration-tests` was doing this already?

**Comment by skellock** [comment]
The tests in our boilerplate are end-to-end tests.

We moved it over to `ignite-ir-boilerplate-2016` when we moved the boilerplate out of here.  What's left in `packages/ignite-integration-tests` is low value and can become unit tests.

Most likely, @jamonholmgren can delete that when he de-lernas this repo.

The reason I like our `ava` tests is because we can use things like `jetpack` and things to do fancy stuff instead of bash tricks.  It's not without it's annoyances though (e.g. `{preferLocal: false}` when calling `execa`.

That's just my preference.  I care more about working tests than I do my preference though.

**Comment by GantMan** [comment]
I'm a fan of moving to JS over bash as well.  I don't think anything was testing like this was.  Perhaps we re-write this test in JS at some later date?

**Comment by jamonholmgren** [comment]
I didn't see this until now. Whoops.

**Pull request merged**
