### PR TITLE
Fix nav bug

### PR DESCRIPTION
**Pull request by GantMan**
This is the fix (tested) for #1001 

We should get appium tests setup on mobile center at some point soon to catch these.

Once someone reviews, we should ship ASAP

### CODE REVIEW

**Comment by skellock** [comment]
Rebasing is can make this cleaner.  🙏 

image

**Comment by GantMan** [comment]
I totally heard you saying that in my head when I saw this.  And now it's confirmed :)

**Comment by skellock** [comment]
Ugh.  Everyone company has a git nazi.  I was wondering when ours would show up.

Turns out, it's me.  😢

**Comment by GantMan** [comment]
image

**Comment by jamonholmgren** [comment]
10 commits for 12 lines changed?

impressed

**Comment by GantMan** [comment]
hahaha, most of those commits came in from an old `git pull`

**Pull request merged**
