### PR TITLE
maps gone for temporary fix

### PR DESCRIPTION
**Pull request by GantMan**
## Please verify the following:
- [x] Everything works on iOS/Android
- [x] `ignite-base` **ava** tests pass
- [x] `fireDrill.sh` passed

## Describe your PR
Bye bye maps, come back soon, we miss you!

### CODE REVIEW

**Comment by ahmed1490** [comment]
just curious. What was this for?

**Comment by GantMan** [comment]
react native maps were broken in brand new ignite projects, until we got the ability to lock versions as of recent ignite, it would always grab from master.   SO we had to rip it out until everyone catches up, and also until our maps install works with latest RN maps.

**Comment by ahmed1490** [comment]
Thanks for explaining :)

**Comment by joaovpmamede** [comment]
I was having some issues in iOS (apparently fixed by this [PR](https://github.com/lelandrichardson/react-native-maps/pull/373)) when trying to install the [react-native-maps](https://github.com/lelandrichardson/react-native-maps).

It seems that we would be fine using the "official" repo with the latest version for react-native 0.29 and using cocoapods. 
Is that correct?

Not sure about the current integration (if any) of cocoapods and Ignite but I managed to make it work by using this [fork](https://github.com/kfiroo/react-native-maps).

**Comment by CharlieIGG** [comment]
@joaovpmamede I've been unable to get maps to work by installing manually... main branch just causes force close, and when I try the fork you suggested I can't even compile the app, with error: 
`com.android.dex.DexException: Multiple dex files define Landroid/support/v7/appcompat/R$anim;`

Any ideas what am I doing wrong. I did clear cache and even re-installed all node_modules...

**Comment by joaovpmamede** [comment]
@CharlieIGG I remember doing the following:

1. add `"react-native-maps": "github:kfiroo/react-native-maps",` or `github:lelandrichardson/react-native-maps` to your `package.json`
2. this [step](https://github.com/kfiroo/react-native-maps/blob/master/docs/installation.md#manually)

Forgot to say that I'm running the iOS version.

**Pull request merged**
