### PR TITLE
Changes ignite plugin config to JSON.

### LINKED ISSUE #688: Convert toml to json for ignite plugin authors
We did this recently for the `ignite/ignite.toml` for apps, but now let's finish this up for `ignite.toml` for plugin authors.

Currently we only use this for defining generators, so it's only present in `ignite-basic-generators`.

The game plan is to call this `ignite.json`.  It'll be optional to have this.  #681 has that fix, so I'd like to get that merged before I do this one.

### PR DESCRIPTION
**Pull request by skellock**
Ignite plugins are now configured with `json` instead of `toml`.

Good bye TOML, we'll meet again in another project.

Fixes #688

### CODE REVIEW

**Comment by GantMan** [comment]
is this backwards compatible?  Does this effect these guys? https://github.com/infinitered/ignite/blob/master/PLUGINS.md

**Comment by skellock** [comment]
Ya, these can all just delete their TOML files.

**Comment by GantMan** [comment]
but then how do they description though?

¯\\_(ツ)_/¯

**Comment by skellock** [comment]
`package.json` in the `description` field.

**Comment by skellock** [comment]
^ also, I may have just invented that just now.  I can't remember if it's thing or not.  😆

**Pull request merged**
