### PR TITLE
Add react-native-config support

### PR DESCRIPTION
**Pull request by ryanlntn**
## Please verify the following:
- [x] Everything works on iOS/Android
- [x] `ignite-base` **ava** tests pass
- [x] `fireDrill.sh` passed

## Describe your PR
Adds [react-native-config](https://github.com/luggit/react-native-config) support to Ignite. Similar to dotenv.

### CODE REVIEW

**Comment by skellock** [comment]
Beautiful!

**Comment by GantMan** [comment]
@ryanlntn if there is no .env file detected, does `react-native-config` fail gracefully?

Do we need to generate a .env file when we generate an app?

**Comment by ryanlntn** [comment]
@GantMan I'm not sure I haven't tried yet. I do think it'd be a good idea to generate a `.env` file regardless. Maybe you could help me figure that out later today?

**Comment by GantMan** [comment]
Sounds like a plan

**Comment by jgkim** [comment]
@GantMan @ryanlntn It doesn't seem like that is the case. Cf. luggit/react-native-config#7

**Comment by GantMan** [comment]
Doesn't or does?  It seems to be a filed issue.  Either way we're updating Ryan's code to place an example `.env` file.  We're beginner friendly 👍

**Comment by jgkim** [comment]
@GantMan Oops, I meant if there is no .env file detected, `react-native-config` **doesn't** fail gracefully. ;)

**Comment by GantMan** [comment]
hahaha, gotcha :)   All good, Ryan will have a fix for us soon.   I've requested that the example secret say "taco" somewhere.   We'll see what bubbles up.

**Pull request merged**
