### PR TITLE
Flatten default navigators

### PR DESCRIPTION
**Pull request by JeroenGoddijn**
## Please verify the following:

- [ ] `yarn ci:test` **jest** tests pass with new tests, if relevant
- [ ] `README.md` has been updated with your changes, if relevant

## Describe your PR
See this [link](https://reactnavigation.org/docs/nesting-navigators/#best-practices-when-nesting).

Having nested navigators has a negative impact on performance, and also causes more issues/challenges with deep-linking.
Hence, I've removed main-navigator.tsx, updated index.ts, and moved all relevant elements from main-navigator to root-navigator,tsx,

I have ran `npx react-native run-android` on a clean install of ignite, and the app works just as it did before the changes.

### CODE REVIEW

**Review by jamonholmgren — CHANGES_REQUESTED** [review]
@JeroenGoddijn Thanks for the PR! Looks good.

Now that the navigators are flattened out, could you change the `RootNavigator` to be named `AppNavigator` instead? That makes more sense to me.

Then I'll get this merged.

**Comment by jamonholmgren** [comment]
I decided to go ahead and make the change myself -- going to deploy it soon. Thanks again!

**Comment by JeroenGoddijn** [comment]
Yeah, no worries. 
Don't understand the name either, is some auto-naming from GitHub. I edited on github.com this time.

Have deeplinking working too, but that needs manual work to work right. So will need time to add that with sufficient comments.

**Review by jamonholmgren — APPROVED** [review]
Looks good!

**Pull request merged**
