### PR TITLE
Removes npm-run-all which causes certain failures

### PR DESCRIPTION
**Pull request by jamonholmgren**
While spinning up a new Ignite app, I ran into some irritating issues where Ignite would fail with:

```shell
$ npm-run-all format:* ''
ERROR: Task not found: ""
```

For some reason, that following `''` is being appended.

I'm having trouble figuring out where, so instead of having `npm-run-all` at all, I'm just calling the format scripts directly and removing the `npm-run-all` package entirely. This is more explicit, removes a dependency, and solves this and IIRC potentially another issue where Windows doesn't work properly expand the `*` if you don't escape it properly.

### CODE REVIEW

**Comment by robinheinze** [comment]
I wonder if this could this be related to #1912

**Comment by jamonholmgren** [comment]
Looks like we're getting a TypeScript error on CI. I replicated it -- something to do with our ErrorBoundary class, which is taken mostly from RN docs.

```
    app/app.tsx:61:12 - error TS2786: 'ErrorBoundary' cannot be used as a JSX component.
      Its instance type 'ErrorBoundary' is not a valid JSX element.
        The types returned by 'render()' are incompatible between these types.
          Type 'import(\"/tmp/ignite-49f777cf87c17424f01054c8db113762/Foo/node_modules/@types/react/index\").ReactNode' is not assignable to type 'React.ReactNode'.
    
    61           <ErrorBoundary catchErrors={\"always\"}>
                  ~~~~~~~~~~~~
```

To debug this, spin up a new app and then run `yarn tsc -p .`.

I don't have time right now, unfortunately, but maybe someone else can carry this forward.

**Comment by jamonholmgren** [comment]
> I wonder if this could this be related to #1912

Could be, @robinheinze!

**Comment by dannyhw** [comment]
@jamonholmgren 

just stumbled onto this and I think I might know the issue with the types

If you check the react native template its including this resolution here: 

```
 "resolutions": {
    "@types/react": "^17"
  },
```

see https://github.com/react-native-community/react-native-template-typescript/blob/main/template/package.json

That's because the types for children changed in react 18 and somehow the types get pulled in via dependencies.

If I add this and resolution and yarn install then the typescript issues are fixed for me

**Pull request merged**
