### PR TITLE
Adds check and rejection for numbers-only project name

### LINKED ISSUE #1116: `ignite new` fails when project name consists entirely of numbers
When creating an ignite project in a project directory that consists entirely of numbers:

    ignite new 100

creation fails with the message

    ✖ failed to add React Native 0.42.0

### PR DESCRIPTION
**Pull request by pekkanikolaus**
Signed-off-by: Pekka Gaiser <pekka@gmx.de>

Fixes #1116. 
This is actually my first pull request _ever_! So excited! :)
Let me know if anything needs correcting.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
> This is actually my first pull request ever! So excited! :)

Wow! That's fantastic! Will review in a bit. Congrats!

**Comment by darinwilson** [comment]
> This is actually my first pull request _ever_!

**Comment by skellock** [comment]
Thanks for the fix!

That's awesome this is your first PR! Well done!

**Comment by ryanlntn** [comment]
> This is actually my first pull request ever!

**Comment by GantMan** [comment]
noice

**Pull request merged**
