### PR TITLE
fix: format ignite doctor generators nicely

### LINKED ISSUE #1490: Clean up ignite doctor generators output
#1478 fixed the generators not showing up, but the output leaves a little to be desired:

image

Let's clean this up and make it look good.

@mikaoelitiana or @arielrodrigues, are you interested in doing this?

### PR DESCRIPTION
**Pull request by mikaoelitiana**
## Please verify the following:

- [x] Everything works on iOS/Android
- [x] `yarn ci:test` **jest** tests pass with new tests, if relevant
- [x] `./docs/` has been updated with your changes, if relevant

## Describe your PR

get uniq generator names and join them for display in `ignite doctor`

fixes #1490

### CODE REVIEW

**Comment by jamonholmgren** [comment]
@mikaoelitiana Thanks a ton! Can you post a screenshot of how it looks with this change?

**Comment by jamonholmgren** [comment]
I think it would be a good idea to keep the keys, like `component`, `navigator`, etc. Perhaps add more rows to the table under the generators row that shows each key-value pair, and output a blank string for the first column of each of those rows.

**Comment by jamonholmgren** [comment]
@mikaoelitiana Would you want to update this PR? I'd love to get it merged.

**Comment by mikaoelitiana** [comment]
I have updated the PR and the output know looks like this: 

Capture d’écran 2020-01-10 à 16 04 35

**Pull request merged**
