### PR TITLE
Prepares the option of using Ignite structure in web projects

### PR DESCRIPTION
**Pull request by sidferreira**
A first step to have Ignite boilerplates for Web projects

This should change nothing on RN projects except  the "React" option on Install context

### CODE REVIEW

**Comment by jamonholmgren** [comment]
Would you mind providing a test or two for this, @sidferreira ?

**Comment by sidferreira** [comment]
Sure! Will do tomorrow morning!

**Comment by jamonholmgren** [comment]
@skellock @GantMan Any additional thoughts before we merge?

**Comment by skellock** [comment]
I vote no for now. (and i don't mean that in a YOU SUCK way either)

### superficial reasons

* this uses `create-react-app`.  which is a boilerplate and brings it's own opinions.
* we don't check that `create-react-app` is installed
* i'm not sure if `create-react-app` supports `--skip-jest`
* if people use `ignite` for web apps now, they still have to have `react-native` installed
* once it is in, we're now supporting it and nobody uses it here

### slightly bigger picture

Here's what the landscape looks like now:

image

With this PR, it becomes this:

image

Where we're hopefully going is like this:

image

@sidferreira I think it's *awesome* you're working on the `create-react-app` version!  And it's not that this PR is wrong, I just think it's a bit too soon to put into the core.

If there's anything I can help you do in your boilerplate, don't hesitate to ask!

**Comment by GantMan** [comment]
yeah, I'm going to be doing boilerplate soon, too.  Best to make the flavors of react stay in the boilerplate.  Let's just move this code there.

**Comment by sidferreira** [comment]
I really agree with @skellock . 
At first, I was expecting to modify only the boilerplate. After that, I noticed I had to modify it in the cli.
At the same time, not proceeding with this PR will basically freeze the ignite-web.
So my opinion depends on how long the CLI change would take...

**Comment by skellock** [comment]
@sidferreira in your `boilerplate.js`, instead of calling https://github.com/infinitered/ignite-ir-boilerplate/blob/master/boilerplate.js#L48, you'd call the function this file instead.

**Comment by skellock** [comment]
Closing for now.  Thx @sidferreira.  Don't hesitate to summon me if you need help on your boilerplate.

**Pull request closed without merging**
