### PR TITLE
Add travis

### PR DESCRIPTION
**Pull request by GantMan**
## Describe your PR
This .travis.yml plus changes (some indicated by @juddey) - helps ignite master run against Facebook master every 24 hours.

As you can see there is a problem in the current build, and this identifies an early warning issue.
image

 
**ALSO SORRY!**

> Whomever merges this PR, please squash it.  I have mannnnny commits, because that's kind of the only way to test against travis ci.

### CODE REVIEW

**Comment by juddey** [comment]
hey @gantman, just reviewed your changes. I've finished my PR locally now, but I think it'll be easier to manage once this has all been merged to master, happy to wait a few days for that to happen.

Just fyi, the PR that I have done will run each generator and verify that the files were created, so there's not much crossover with what you've done.

**Comment by GantMan** [comment]
I'll self-merge!

**Comment by GantMan** [comment]
image

**Comment by juddey** [comment]
Wouldn't want to run into this beast in a conflict resolution! 👹

**Pull request merged**
