### PR TITLE
Move font sizes into Font from Metrics.

### LINKED ISSUE #49: Thoughts on changing font size location
I find myself doing this very often:

```css
  title: {
    fontFamily: Fonts.bold,
    fontSize: Metrics.fonts.medium,
    color: Colors.charcoal
  },
```

I think it would feel a lot "cleaner" to do this:

```css
  title: {
    fontFamily: Fonts.bold,
    fontSize: Fonts.size.medium,
    color: Colors.charcoal
  },
```

It would be a relatively easy change. When i thing of "font size" i don't think of the "metrics" object, i think of the "font" object.

### Make sure verify the following before submitting an issue.

- [x] Issue does not already exist
- [x] You have example code or some other reproduce experiment that we can verify

### PR DESCRIPTION
**Pull request by markrickert**
Closes #49.

Discuss.

### Pull-Request Checklist

- [x] Works on iOS/Android/XDE
- [x] Tests Pass (run: `npm run test && npm run test:client`)
- [x] Code is StandardJS compliant (run: `npm run lint`)

### CODE REVIEW

**Comment by skellock** [comment]
Terrible idea.

**Comment by skellock** [comment]
image

just kidding.  love it.

**Comment by GantMan** [comment]
I like it, but let me play devil's advocate.

For an icon I would use `Metrics.icon.regular`, but for a font I'd use `Fonts.size.title`?   Then, would I be crazy to expect an image to be something like `Images.size.thumbnail`?

I like the idea of fonts containing font sizes for simple imports, but how do we best illustrate that font metrics belong outside of Metrics?

**Comment by skellock** [comment]
I like that too.  `Images.size.massive`.  That feels right as well.

For other font metrics not in our examples, I'd expect for them to live inside Fonts as well.  `lineHeight` for example.

**Comment by markrickert** [comment]
I'm basically saying that like things should be grouped together. Fonts have properties: `family`, `size`, etc. and it feels more "natural" to fo `Font.size.regular` instead of `Metrics.fonts.regular`. Typing `Metrics.fonts.regular` doesn't explicitly state that we're getting a `size` there... it infers a font object of size and face in my opinion.

**Comment by GantMan** [comment]
@markrickert - can you add `Images.size.large` and perhaps use it for the progressive component, so that we entrench this pattern as we accept the PR?

**Comment by markrickert** [comment]
I added an example of image sizes. Check it out and let e know what you think.

**Pull request merged**
