### PR TITLE
Ignite X release commit

### PR DESCRIPTION
**Pull request by lindboe**
Merge up PR for Ignite X release.

Semantic-release dry run generated this. I'm not sure why it formatted the bullets for the BREAKING CHANGE section like that, the first line is not a bullet in the commit, but I'm also not sure how to fix it so it seems fine to leave it be, it's still readable:

```
### Bug Fixes

    * boilerplate: expo-router initialize i18n (#2791 by @frankcalise) (a00113e)
    * boilerplate: Make icon default color explicit, and respond to dark mode (#2795 by @lindboe) (b82398d)
    * cli: improper MST removal when using CLI prompt, new arch compat (#2785 by @frankcalise) (3956652)
    * remove snackify command and references (#2763 by @frankcalise) (09671e8)

### Features

    * Ignite X with Expo 51 (005ef05)
    * boilerplate: Toggle component refactored to Checkbox, Radio and Switch (#2667 by @frankcalise) (54f5208)
    * cli: expo-router option (#2727 by @frankcalise) (8bea1f9), closes #2731
    * cli: generator options --dir and --case  (#2726 by @frankcalise) (dff3d24)
    * Theming: Adds theming support with documentation. (#2636) (a1ae047)
    * v10: cng default (#2641) (c7d998d)
    * v10: Remove MobX-State-Tree flag for non-demo projects (#2647 by @Jpoliachik) (a738243)
    * add MMKV for v10 (#2660 by @frankcalise) (9164e5e)

### BREAKING CHANGES

    * Ignite X is out now! This update adds:
    * Expo Prebuild as default
    * Dark mode support
    * Static routing with Expo Router
    * Flexible generator directory support
    * Option to remove mobx-state-tree
    * AsyncStorage->MMKV
    * New i18n configuration with react-i18next
    * Lint configuration updates
    * Toggle component → Checkbox, Radio, and Switch
    * Improved keyboard avoidance
    * Component test example configuration

Read all about it in our blog article!

https://shift.infinite.red/what-is-ignite-x-9ecde0b34d75
```

### CODE REVIEW

**Review by frankcalise — APPROVED** [review]
👏 👏 👏

**Review by mazenchami — APPROVED** [review]
🎉 🚀 amazing job team!!

**Comment by Jpoliachik** [comment]
woo!!

**Pull request merged**
