### PR TITLE
Upgrade to react native screens v3

### PR DESCRIPTION
**Pull request by vantuan88291**
## Please verify the following:

- [x] `yarn ci:test` **jest** tests pass with new tests, if relevant
- [x] `README.md` has been updated with your changes, if relevant

## Describe your PR
- Add dispatch action to navigation-utilities
- Upgrade react-navigation
- Upgrade to react native screens v3, remove enableScreens(), its will enable by default, reference: https://github.com/software-mansion/react-native-screens/releases/tag/3.0.0

### CODE REVIEW

**Comment by jamonholmgren** [comment]
@vantuan88291 Thanks for the PR! Could you resolve conflicts please?

**Comment by tuanlvntq** [comment]
> @vantuan88291 Thanks for the PR! Could you resolve conflicts please?

I resolved the conflict. Thanks

**Comment by jamonholmgren** [comment]
Thanks so much @vantuan88291 !

**Pull request merged**
