### PR TITLE
docs: add Robin's CR 2024 talk link

### PR DESCRIPTION
**Pull request by frankcalise**
## Please verify the following:

- [ ] `yarn test` **jest** tests pass with new tests, if relevant
- [ ] `yarn lint` **eslint** checks pass with new code, if relevant
- [ ] `yarn format:check` **prettier** checks pass with new code, if relevant
- [x] `README.md` (or relevant documentation) has been updated with your changes

## Describe your PR
- Updates the docs with Robin's CR 2024 talk link to the YouTube recording

### CODE REVIEW

**Review by mazenchami — APPROVED** [review]

**Comment by GantMan** [comment]
Feedback - can you make this 4 thumbnails -  It's easy to scroll past it as text.

**Comment by GantMan** [comment]
Takes longer to do that, but probably would add 10x on clicks

**Comment by GantMan** [comment]
I like it.  I would approve as is-  @jamonholmgren @robinheinze ?

We can always improve later

**Review by jamonholmgren — APPROVED** [review]

**Pull request merged**
